### ISSUE TITLE
Pass in a `null` token.

### ISSUE THREAD

**Issue by waltfy** [gitterHQ/node-gitter#10]
Should handle the case in which `token` is neither present nor valid.
https://github.com/gitterHQ/node-gitter/blob/e962f077791c44ac82b4576204c4c3f9b333b877/lib/gitter.js

**Comment by MajkelKorczak** [comment]
I think it's completed by #22 pull request.

**Comment by MadLittleMods** [comment]
Thanks @MajkelKorczak, #22 will make things error out earlier at least 😀
