### ISSUE TITLE
node-gitter disconnects from faye streaming after ~30 minutes

### ISSUE THREAD

**Issue by jaredallard** [gitterHQ/node-gitter#14]
Replicate by connecting to a room, than listening. After about 30 minutes or so it stops receiving messages.

EDIT:

It seems it can take longer, however after an extended period of time node-gitter stops getting messages.

**Comment by malditogeek** [comment]
@RainbowDashDC hi!

Question, what method are you using? `room.streaming()` or `room.listen()`?

**Comment by RainbowDashDC** [comment]
@malditogeek using `room.listen()`

**Comment by malditogeek** [comment]
@RainbowDashDC I'd recommend you to switch to `room.streaming()` instead: https://github.com/gitterHQ/node-gitter#listen-for-chatmessages-events-or-users-in-a-room

The difference is that `streaming()` connects directly to Faye, our main message broker. `listen()` on the other hand goes through an http streaming bridge which might introduce latency and other issues.

Sorry about that. Exposing the two mechanisms is a bit confusing, we should probably deprecate `listen()` soon as it's main purpose was to be used from the CLI.

**Comment by RainbowDashDC** [comment]
@malditogeek Thank you for the quick response! I'll switch right over to that, and I agree with deprecating that. If you have something that can do the same thing but not have issues it's better to use that, am I right :P 

Anyways, I reiterate, thank you!
