### ISSUE TITLE
long messages throw an exception

### ISSUE THREAD

**Issue by huafu** [gitterHQ/node-gitter#6]
Sometimes with "big" messages the process arrives [here](https://github.com/gitterHQ/node-gitter/blob/master/lib/client.js#L133) with only a part of the message, so that the `JSON.parse` called [here](https://github.com/gitterHQ/node-gitter/blob/master/lib/client.js#L135) is failing, and then any tool using this lib just stops working suddenly with no error message, while the heartbeat is still received but not the end of the message.

What I call long message is actually not that long, something like 5 lines of GFM

**Comment by malditogeek** [comment]
Merged ages ago, closing this.
